# Generated by Django 3.1.2 on 2021-09-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='permissions',
            field=models.ManyToManyField(related_name='user_group_set', related_query_name='user_group', to='auth.Permission', verbose_name='permissions'),
        ),
    ]
