# Generated by Django 3.1.2 on 2021-09-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('frame_id', models.FloatField()),
                ('tracking_id', models.FloatField()),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Stream Analytic',
                'verbose_name_plural': 'Stream Analytics',
                'proxy': False,
            },
        ),
    ]
