# Generated by Django 3.1.2 on 2021-09-15 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_organizations', '0001_initial'),
        ('outlets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='app_organizations.apporganization'),
        ),
    ]
